import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

def generate_complaint_pdf(case_data: dict, output_path: str):
    doc = SimpleDocTemplate(output_path, pagesize=letter)
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=18,
        spaceAfter=12,
        alignment=1 # Center
    )
    
    elements = []
    
    # Header
    elements.append(Paragraph("Cybercrime Complaint Report", title_style))
    elements.append(Paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
    elements.append(Spacer(1, 12))
    
    # Case Details
    elements.append(Paragraph("<b>Case Information</b>", styles['Heading2']))
    data = [
        ["Case ID:", case_data.get("case_id")],
        ["Issue Type:", case_data.get("issue_type")],
        ["Severity:", case_data.get("severity")],
        ["Platform:", case_data.get("platform") or "N/A"],
        ["Account Username:", case_data.get("account_username") or "N/A"],
        ["Incident Date:", case_data.get("incident_date") or "N/A"],
        ["Status:", case_data.get("status")]
    ]
    
    t = Table(data, colWidths=[120, 300])
    t.setStyle(TableStyle([
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 12))
    
    # Description
    elements.append(Paragraph("<b>Incident Description</b>", styles['Heading2']))
    elements.append(Paragraph(case_data.get("description") or "No description provided.", styles['Normal']))
    elements.append(Spacer(1, 12))
    
    # Evidence
    elements.append(Paragraph("<b>Evidence List</b>", styles['Heading2']))
    evidence = case_data.get("evidence", [])
    if evidence:
        ev_data = [["File Name", "Upload Timestamp"]]
        for e in evidence:
            ev_data.append([e["file_name"], e["upload_timestamp"]])
        
        ev_table = Table(ev_data, colWidths=[250, 170])
        ev_table.setStyle(TableStyle([
            ('HEADER', (0, 0), (-1, 0), colors.whitesmoke),
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('PADDING', (0, 0), (-1, -1), 6),
        ]))
        elements.append(ev_table)
    else:
        elements.append(Paragraph("No evidence uploaded.", styles['Normal']))
    
    elements.append(Spacer(1, 24))
    elements.append(Paragraph("<i>This document is generated by SentinelAI Complaint Assistant.</i>", styles['Italic']))
    
    doc.build(elements)
    return output_path
